version: '2.2'

services:
  elasticsearch:
      # TODO MVR update to a newer version of elastic
      image: keybird/beagle-elastic:5.6.2
      environment:
        - cluster.name=beagle-cluster
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - esdata:/usr/share/elasticsearch/data
      ports:
        - "9200:9200"
        - "9300:9300"
  beagledb:
    # TODO MVR update to a newer version of postgres
    image: postgres:9.6.7
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=beagle
      - POSTGRES_USER=beagleuser
      - POSTGRES_PASSWORD=beaglepassword
  # TODO MVR allow/figure out how to define more ram
  app:
    image: keybird/beagle:latest
    depends_on:
      - beagledb
    volumes:
      - beagledata:/opt/beagle
    ports:
      - "8080:8080"
      - "1044:1044"
    links:
      - beagledb
      - elasticsearch
    environment:
      - "SPRING_PROFILES_ACTIVE=container"
      - DATABASE_HOST=beagledb
      - DATABASE_USER=beagleuser
      - DATABASE_PASSWORD=beaglepassword
      - DATABASE_NAME=beagle
      - DATABASE_PORT=5432
      - ELASTIC_URLS=http://elasticsearch:9200
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=changeme
      - WORKING_DIRECTORY=/opt/beagle

volumes:
  esdata:
    driver: local
  beagledata:
    driver: local
