version: '2.2'

services:
  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:5.6.0
      environment:
        - cluster.name=beagle-cluster
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - esdata:/usr/share/elasticsearch/data
      ports:
        - "9200:9200"
        - "9300:9300"
  mysql:
    image: mysql:5.7.20
    command: mysqld --max_allowed_packet=25M
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=p4SSW0rd
      - MYSQL_DATABASE=beagle
      - MYSQL_USER=beagleuser
      - MYSQL_PASSWORD=beaglepassword
  # TODO MVR allow/figure out how to define more ram
  app:
    image: keybird/beagle:latest
    depends_on:
      - mysql
    volumes:
      - beagledata:/opt/beagle
    ports:
      - "8080:8080"
    links:
      - mysql
      - elasticsearch
    environment:
      - "SPRING_PROFILES_ACTIVE=container,test"
      - DATABASE_HOST=mysql
      - DATABASE_USER=beagleuser
      - DATABASE_PASSWORD=beaglepassword
      - DATABASE_NAME=beagle
      - DATABASE_PORT=3306
      - ELASTIC_URLS=http://elasticsearch:9200
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=changeme
      - WORKING_DIRECTORY=/opt/beagle

volumes:
  esdata:
    driver: local
  beagledata:
    driver: local
