version: 2
jobs:
  build:
    working_directory: ~/beagle-repository

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout

      - restore_cache:
          key: beagle-repository-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: beagle-repository-{{ checksum "pom.xml" }}
      
      - run: mvn validate

      - run: mvn test-compile

      - run: mvn verify

      - run: mvn package -DskipTests
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/beagle-0.0.1-SNAPSHOT.jar

      - setup_remote_docker

      # Login
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      # build   the application image
      - run: docker build --build-arg JAR_FILE=target/beagle-0.0.1-SNAPSHOT.jar -t keybird/beagle:${CIRCLE_BRANCH/\//-} .

      # deploy the image
      - run: docker push keybird/beagle:${CIRCLE_BRANCH/\//-}