version: 2
jobs:
  build:
    working_directory: ~/beagle-repository

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    environment:
      - MAVEN_OPTS: -Xmx2048m -XX:ReservedCodeCacheSize=512m

    steps:

      - checkout

      - restore_cache:
          key: beagle-repository-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: beagle-repository-{{ checksum "pom.xml" }}

      - run: mvn validate

      - run: mvn test-compile

      - run: mvn verify

      - run: mvn package -DskipTests

      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/surefire-reports

      - store_artifacts:
          path: target/beagle-0.0.1-SNAPSHOT.jar

      - setup_remote_docker

      # build the application image
      - run: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            export DOCKERHUB_TAG=${CIRCLE_BRANCH/\//-}-${CIRCLE_SHA1}
            case "${CIRCLE_BRANCH}" in
                master)
                  echo "Building docker image with tag ${DOCKERHUB_TAG} and latest."
                  docker build --build-arg JAR_FILE=target/beagle-0.0.1-SNAPSHOT.jar -t keybird/beagle:${DOCKERHUB_TAG} .
                  docker tag keybird/beagle:${DOCKERHUB_TAG} keybird/beagle:latest
                  docker push keybird/beagle:${DOCKERHUB_TAG}
                  docker push keybird/beagle:latest
                  ;;
                *)
                  echo "Building docker image with tag ${DOCKERHUB_TAG}."
                  docker build --build-arg JAR_FILE=target/beagle-0.0.1-SNAPSHOT.jar -t keybird/beagle:${DOCKERHUB_TAG} .
                  docker push keybird/beagle:${DOCKERHUB_TAG}
                  ;;
              esac

  e2e:
    working_directory: ~/beagle-repository
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout

      # enable docker in docker
      - setup_remote_docker

      # Startup application
      - run: |
          export DOCKERHUB_TAG=${CIRCLE_BRANCH/\//-}-${CIRCLE_SHA1}

          # Override settings for e2e testing
          cat > docker-compose.override.yml <<EOF
          version: '2.2'
          services:
            app:
              image: keybird/beagle:${DOCKERHUB_TAG}
              container_name: beagle
          EOF
          cat docker-compose.override.yml

          # Startup environment
          docker-compose up -d

          # Wait for container
          NEXT_WAIT_TIME=0
          until $( docker exec beagle curl http://localhost:8080 > /dev/null 2>&1 ) || [ $NEXT_WAIT_TIME -eq 20 ]; do
             sleep $(( NEXT_WAIT_TIME++ ))
          done

      # Prepare e2e tests
      - run: |
          docker create -v /repo --name source alpine:3.4 /bin/true
          docker cp . source:/repo

      # Run e2e tests
      - run: |
          docker run --network container:beagle --volumes-from source -w /repo keybird/beagle-e2e:latest .circleci/e2e.sh

      # Copy test results back
      - run:
          command: |
            mkdir -p target/e2e
            docker cp source:/repo/target/screenshots target/e2e
          when: always

      # Finally collect artifacts
      - store_artifacts:
          path: target/e2e/**

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - e2e:
          requires:
            - build